import React, { useState, useEffect } from 'react';

interface Alert {
  id: string;
  type: 'error' | 'warning' | 'info' | 'success';
  title: string;
  description: string;
  timestamp: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  assignedTo: string;
  category: 'security' | 'regulatory' | 'assessment' | 'training' | 'checklist' | 'audit';
  acknowledged: boolean;
  resolved: boolean;
  autoGenerated: boolean;
  relatedItems?: string[];
}

interface ComplianceAlertsProps {
  alerts?: Alert[];
  realTimeEnabled?: boolean;
  className?: string;
}

export const ComplianceAlerts: React.FC<ComplianceAlertsProps> = ({
  alerts = mockAlerts,
  realTimeEnabled = false,
  className = ''
}) => {
  const [filteredAlerts, setFilteredAlerts] = useState<Alert[]>(alerts);
  const [selectedFilter, setSelectedFilter] = useState<'all' | 'critical' | 'high' | 'unacknowledged'>('all');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [showAcknowledged, setShowAcknowledged] = useState(false);
  const [autoRefresh, setAutoRefresh] = useState(realTimeEnabled);

  // Mock real-time alerts for demo
  useEffect(() => {
    if (!autoRefresh) return;

    const interval = setInterval(() => {
      // Simulate new alerts
      const newAlert: Alert = {
        id: `alert-${Date.now()}`,
        type: Math.random() > 0.7 ? 'warning' : 'info',
        title: 'System Alert',
        description: 'Automated compliance check completed',
        timestamp: new Date().toISOString(),
        severity: Math.random() > 0.8 ? 'high' : 'medium',
        assignedTo: 'System',
        category: 'audit',
        acknowledged: false,
        resolved: false,
        autoGenerated: true
      };

      if (Math.random() > 0.6) {
        setFilteredAlerts(prev => [newAlert, ...prev.slice(0, 49)]); // Keep last 50 alerts
      }
    }, 30000); // Every 30 seconds

    return () => clearInterval(interval);
  }, [autoRefresh]);

  const getAlertIcon = (type: string) => {
    switch (type) {
      case 'error': return '🚨';
      case 'warning': return '⚠️';
      case 'info': return 'ℹ️';
      case 'success': return '✅';
      default: return '📢';
    }
  };

  const getAlertColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'border-sov-red bg-sov-red/5';
      case 'high': return 'border-sov-red/50 bg-sov-red/5';
      case 'medium': return 'border-sov-gold bg-sov-gold/5';
      case 'low': return 'border-sov-green bg-sov-green/5';
      default: return 'border-gray-600 bg-gray-800/50';
    }
  };

  const getAlertTextColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'text-sov-red';
      case 'high': return 'text-sov-red';
      case 'medium': return 'text-sov-gold';
      case 'low': return 'text-sov-green';
      default: return 'text-sov-light';
    }
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'security': return '🔒';
      case 'regulatory': return '⚖️';
      case 'assessment': return '📋';
      case 'training': return '🎓';
      case 'checklist': return '✅';
      case 'audit': return '🔍';
      default: return '📢';
    }
  };

  const acknowledgeAlert = (alertId: string) => {
    setFilteredAlerts(prev => 
      prev.map(alert => 
        alert.id === alertId ? { ...alert, acknowledged: true } : alert
      )
    );
  };

  const resolveAlert = (alertId: string) => {
    setFilteredAlerts(prev => 
      prev.map(alert => 
        alert.id === alertId ? { ...alert, resolved: true, acknowledged: true } : alert
      )
    );
  };

  const dismissAlert = (alertId: string) => {
    setFilteredAlerts(prev => prev.filter(alert => alert.id !== alertId));
  };

  const filteredData = filteredAlerts.filter(alert => {
    if (selectedFilter !== 'all' && alert.severity !== selectedFilter) return false;
    if (!showAcknowledged && alert.acknowledged) return false;
    if (selectedCategory !== 'all' && alert.category !== selectedCategory) return false;
    if (selectedFilter === 'unacknowledged' && alert.acknowledged) return false;
    return true;
  });

  const alertStats = {
    total: filteredAlerts.length,
    critical: filteredAlerts.filter(a => a.severity === 'critical').length,
    high: filteredAlerts.filter(a => a.severity === 'high').length,
    unacknowledged: filteredAlerts.filter(a => !a.acknowledged).length,
    resolved: filteredAlerts.filter(a => a.resolved).length
  };

  return (
    <div className={`bg-sov-dark-alt p-6 rounded-lg shadow-lg border border-gray-700 ${className}`}>
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className="text-xl font-semibold text-sov-light">Compliance Alerts</h3>
          <p className="text-sm text-sov-light-alt mt-1">
            Real-time compliance monitoring and notifications
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <div className="flex items-center space-x-2">
            <div className={`w-3 h-3 rounded-full ${autoRefresh ? 'bg-sov-green animate-pulse' : 'bg-gray-500'}`}></div>
            <span className="text-sm text-sov-light-alt">
              {autoRefresh ? 'Real-time' : 'Manual'}
            </span>
          </div>
          <button
            onClick={() => setAutoRefresh(!autoRefresh)}
            className={`px-3 py-1 rounded text-sm font-semibold transition-colors ${
              autoRefresh 
                ? 'bg-sov-green text-sov-dark hover:bg-sov-green/80' 
                : 'bg-gray-700 text-sov-light hover:bg-gray-600'
            }`}
          >
            {autoRefresh ? 'Auto: ON' : 'Auto: OFF'}
          </button>
        </div>
      </div>

      {/* Alert Statistics */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
        <div className="text-center p-3 bg-sov-dark rounded-lg border border-gray-700">
          <div className="text-2xl font-bold text-sov-light">{alertStats.total}</div>
          <div className="text-xs text-sov-light-alt">Total Alerts</div>
        </div>
        <div className="text-center p-3 bg-sov-dark rounded-lg border border-gray-700">
          <div className="text-2xl font-bold text-sov-red">{alertStats.critical}</div>
          <div className="text-xs text-sov-light-alt">Critical</div>
        </div>
        <div className="text-center p-3 bg-sov-dark rounded-lg border border-gray-700">
          <div className="text-2xl font-bold text-sov-gold">{alertStats.high}</div>
          <div className="text-xs text-sov-light-alt">High Priority</div>
        </div>
        <div className="text-center p-3 bg-sov-dark rounded-lg border border-gray-700">
          <div className="text-2xl font-bold text-sov-accent">{alertStats.unacknowledged}</div>
          <div className="text-xs text-sov-light-alt">Unacknowledged</div>
        </div>
        <div className="text-center p-3 bg-sov-dark rounded-lg border border-gray-700">
          <div className="text-2xl font-bold text-sov-green">{alertStats.resolved}</div>
          <div className="text-xs text-sov-light-alt">Resolved</div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 mb-6">
        <div className="flex bg-sov-dark border border-gray-600 rounded-lg overflow-hidden">
          {[
            { key: 'all', label: 'All', count: filteredAlerts.length },
            { key: 'critical', label: 'Critical', count: filteredAlerts.filter(a => a.severity === 'critical').length },
            { key: 'high', label: 'High', count: filteredAlerts.filter(a => a.severity === 'high').length },
            { key: 'unacknowledged', label: 'Unacknowledged', count: filteredAlerts.filter(a => !a.acknowledged).length }
          ].map(filter => (
            <button
              key={filter.key}
              onClick={() => setSelectedFilter(filter.key as any)}
              className={`px-3 py-2 text-sm font-semibold ${
                selectedFilter === filter.key ? 'bg-sov-accent text-sov-dark' : 'text-sov-light hover:bg-gray-700'
              }`}
            >
              {filter.label} ({filter.count})
            </button>
          ))}
        </div>

        <select
          value={selectedCategory}
          onChange={(e) => setSelectedCategory(e.target.value)}
          className="bg-sov-dark border border-gray-600 text-sov-light px-3 py-2 rounded-lg text-sm"
        >
          <option value="all">All Categories</option>
          <option value="security">Security</option>
          <option value="regulatory">Regulatory</option>
          <option value="assessment">Assessment</option>
          <option value="training">Training</option>
          <option value="checklist">Checklist</option>
          <option value="audit">Audit</option>
        </select>

        <label className="flex items-center space-x-2 text-sm text-sov-light">
          <input
            type="checkbox"
            checked={showAcknowledged}
            onChange={(e) => setShowAcknowledged(e.target.checked)}
            className="rounded border-gray-600 bg-sov-dark text-sov-accent focus:ring-sov-accent"
          />
          <span>Show acknowledged</span>
        </label>
      </div>

      {/* Alerts List */}
      <div className="space-y-3 max-h-96 overflow-y-auto">
        {filteredData.length === 0 ? (
          <div className="text-center text-sov-light-alt py-8">
            No alerts match the current filter criteria
          </div>
        ) : (
          filteredData.map(alert => (
            <div 
              key={alert.id} 
              className={`p-4 rounded-lg border transition-all duration-200 ${
                getAlertColor(alert.severity)
              } ${alert.acknowledged ? 'opacity-75' : ''}`}
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-start space-x-3">
                  <span className="text-2xl">{getAlertIcon(alert.type)}</span>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <h4 className={`font-semibold ${getAlertTextColor(alert.severity)}`}>
                        {alert.title}
                      </h4>
                      <span className="px-2 py-1 rounded-full text-xs font-semibold bg-sov-dark text-sov-light">
                        {getCategoryIcon(alert.category)} {alert.category}
                      </span>
                      {alert.autoGenerated && (
                        <span className="px-2 py-1 rounded-full text-xs font-semibold bg-sov-accent/20 text-sov-accent">
                          Auto
                        </span>
                      )}
                    </div>
                    <p className="text-sm text-sov-light-alt mb-2">{alert.description}</p>
                    <div className="flex items-center space-x-4 text-xs text-sov-light-alt">
                      <span>
                        {new Date(alert.timestamp).toLocaleString()}
                      </span>
                      <span>Assigned to: {alert.assignedTo}</span>
                      {alert.acknowledged && (
                        <span className="text-sov-green">✓ Acknowledged</span>
                      )}
                      {alert.resolved && (
                        <span className="text-sov-green">✓ Resolved</span>
                      )}
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-2">
                  {!alert.resolved && (
                    <>
                      {!alert.acknowledged && (
                        <button
                          onClick={() => acknowledgeAlert(alert.id)}
                          className="px-3 py-1 bg-sov-accent/20 text-sov-accent rounded text-sm font-semibold hover:bg-sov-accent/30 transition-colors"
                        >
                          Acknowledge
                        </button>
                      )}
                      <button
                        onClick={() => resolveAlert(alert.id)}
                        className="px-3 py-1 bg-sov-green/20 text-sov-green rounded text-sm font-semibold hover:bg-sov-green/30 transition-colors"
                      >
                        Resolve
                      </button>
                    </>
                  )}
                  <button
                    onClick={() => dismissAlert(alert.id)}
                    className="px-2 py-1 bg-gray-700 text-sov-light rounded text-sm hover:bg-gray-600 transition-colors"
                  >
                    ✕
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Quick Actions */}
      <div className="mt-6 p-4 bg-sov-dark rounded-lg border border-gray-700">
        <h4 className="text-lg font-semibold mb-3 text-sov-light">Quick Actions</h4>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <button className="p-3 bg-sov-accent/10 text-sov-accent rounded-lg hover:bg-sov-accent/20 transition-colors text-sm font-semibold">
            Bulk Acknowledge
          </button>
          <button className="p-3 bg-sov-green/10 text-sov-green rounded-lg hover:bg-sov-green/20 transition-colors text-sm font-semibold">
            Mark All Resolved
          </button>
          <button className="p-3 bg-sov-gold/10 text-sov-gold rounded-lg hover:bg-sov-gold/20 transition-colors text-sm font-semibold">
            Configure Rules
          </button>
          <button className="p-3 bg-sov-dark-alt border border-gray-600 text-sov-light rounded-lg hover:bg-gray-700 transition-colors text-sm font-semibold">
            Export Alerts
          </button>
        </div>
      </div>
    </div>
  );
};

// Mock data for demonstration
const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    type: 'error',
    title: 'PCI DSS Assessment Due',
    description: 'Annual PCI DSS assessment is overdue by 15 days',
    timestamp: '2024-11-02T14:30:00Z',
    severity: 'critical',
    assignedTo: 'Security Team',
    category: 'assessment',
    acknowledged: false,
    resolved: false,
    autoGenerated: true
  },
  {
    id: 'alert-002',
    type: 'warning',
    title: 'Training Deadline Approaching',
    description: 'AML training deadline in 3 days - 5 users pending completion',
    timestamp: '2024-11-02T10:15:00Z',
    severity: 'high',
    assignedTo: 'HR Team',
    category: 'training',
    acknowledged: false,
    resolved: false,
    autoGenerated: true
  },
  {
    id: 'alert-003',
    type: 'info',
    title: 'Compliance Checklist Updated',
    description: 'Q4 compliance checklist has been updated with new requirements',
    timestamp: '2024-11-01T16:20:00Z',
    severity: 'medium',
    assignedTo: 'Compliance Team',
    category: 'checklist',
    acknowledged: true,
    resolved: false,
    autoGenerated: false
  },
  {
    id: 'alert-004',
    type: 'warning',
    title: 'NACHA Rules Update',
    description: 'New NACHA operating rules take effect next month - review required',
    timestamp: '2024-10-31T09:00:00Z',
    severity: 'high',
    assignedTo: 'Operations Team',
    category: 'regulatory',
    acknowledged: true,
    resolved: false,
    autoGenerated: true
  },
  {
    id: 'alert-005',
    type: 'success',
    title: 'Security Scan Completed',
    description: 'Weekly vulnerability scan completed - no critical issues found',
    timestamp: '2024-11-02T08:00:00Z',
    severity: 'low',
    assignedTo: 'IT Team',
    category: 'security',
    acknowledged: true,
    resolved: true,
    autoGenerated: true
  }
];
